### ISSUE TITLE
Can the length and width of the text input box be larger?

### ISSUE THREAD

**Issue by corwin1949** [cjlm/send-to-workflowy#10]
I currently use Tampermonkey to set the width of the text input box to 550px and the height to 300px.

After this setting:

1. I can enter more content
2. I can create multiple lists in workflowy by creating line breaks in the input box. Once the input box is bigger, I can send multiple lists to workflowy at once without waiting for the "send" to finish, eliminating the waiting time.

**Comment by cjlm** [comment]
I could look into persisting the input box once it's resized... Not sure how feasible that is. Nice request though, thanks!

**Comment by corwin1949** [comment]
> I could look into persisting the input box once it's resized... Not sure how feasible that is. Nice request though, thanks!

In fact, in the current version, sections separated by carriage returns have been able to create different workflow nodes.

But because the current input box is relatively small, write more than a few paragraphs of text inconvenience.

Of course, there may be other considerations in setting up such an input box, I'm just offering a possible usage.

Thanks for the tools. I had fun with them😄

**Comment by cjlm** [comment]
> In fact, in the current version, sections separated by carriage returns have been able to create different workflow nodes.

Yes, I'm glad you're using that, I added it in the last release. It supports indentation for nested nodes too :-)

**Comment by corwin1949** [comment]
[**@cjlm**](https://github.com/cjlm) commented on [2021年12月10日 GMT+8 下午7:05](https://github.com/cjlm/send-to-workflowy/issues/10#issuecomment-990875437 "2021-12-10T11:05:35Z - Replied by Github Reply Comments"):
> > In fact, in the current version, sections separated by carriage returns have been able to create different workflow nodes.
> 
> Yes, I'm glad you're using that, I added it in the last release. It supports indentation for nested nodes too :-)

Awesome, perfect.
